### ISSUE TITLE
What PHP vs are you writing this in?

### ISSUE THREAD

**Issue by findborg** [safesploit/Doogle#1]
I have seen some other versions.  But,  they quit working with the newer versions of php.  So,  I would like to know if you are at least using php7 or above.

**Comment by safesploit** [comment]
I believe the entire project was compliant with PHP 7.3, I personally developed with v7.4.

When developing Doogle I did not take precautions for PHP 8, but unless major changes are made between v7 and v8 then it should work fine.

**Comment by safesploit** [comment]
I can confirm v1.0.0-beta.1 does not work on PHP 8.0 or 8.1.
