### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [safesploit/Doogle#23]
Do I need to setup docker to make this script work?

Joseph

**Comment by safesploit** [comment]
No, when I wrote the setup and usage guide I intended on Docker being used for easier testing than deploying a LAMP stack. As such you can deploy by setting up the LAMP stack yourself.

[LAMP Stack Setup](https://github.com/safesploit/doogle?tab=readme-ov-file#server-setup)
