### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by RedWilly** [safesploit/Doogle#5]
Does this search engine follow robots.txt file or can it ignore and index it either way.

Trying to index my blogspot domain but because of the robots.txt file I can't do that.. any way to allow me to index the site while ignoring the robot.txt

**Comment by safesploit** [comment]
I don't remember programming support to check the `robots.txt` into Doogle. Could you provide the `robots.txt` and a screenshot of your `sites` table?

I will test it against my website, but I don't understand how Doogle could currently be respecting `robots.txt` unless the blog uses a closed web server.

**Comment by RedWilly** [comment]
Yeah I sorry the mistake was from my end. It now working has it should
